env:
  global:
    - SWIFT_VERSION=swift-DEVELOPMENT-SNAPSHOT-2018-10-24-a
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode10
      before_install:
        - pip install lit
        - curl -O "https://swift.org/builds/development/xcode/${SWIFT_VERSION}/${SWIFT_VERSION}-osx.pkg"
        - sudo installer -pkg "${SWIFT_VERSION}-osx.pkg" -target /
        - export PATH="/Library/Developer/Toolchains/${SWIFT_VERSION}.xctoolchain/usr/bin:${PATH}"
      script:
        - make testall
    - os: linux
      language: generic
      sudo: required
      # Note: trusty is Ubuntu 14.04.
      dist: trusty
      before_install:
        - sudo pip install lit
        - sudo apt-get install clang libblocksruntime-dev libicu-dev
        - wget "https://swift.org/builds/development/ubuntu1404/${SWIFT_VERSION}/${SWIFT_VERSION}-ubuntu14.04.tar.gz"
        - tar xzf "${SWIFT_VERSION}-ubuntu14.04.tar.gz"
        - export PATH="${PWD}/${SWIFT_VERSION}-ubuntu14.04/usr/bin:${PATH}"
        - export LD_LIBRARY_PATH="${PWD}/${SWIFT_VERSION}-ubuntu14.04/usr/lib:${LD_LIBRARY_PATH}"
        - export LD_LIBRARY_PATH="${PWD}/${SWIFT_VERSION}-ubuntu14.04/usr/lib/swift/linux:${LD_LIBRARY_PATH}"
        # - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - make testall
